<?php
session_start();
include 'menu_pyrbdome.php'; // Include menu script to show menu bar.
?>

<!-- Specify doctype as HTML and set language to English. -->
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Sets character encoding to UTF-8 for proper rendering of text content, and set viewport properties to device width -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Include Bootstrap CSS for pre designed components for responsive websites to enhance website aesthetic -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

    <!-- CSS Reset -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">

    <!-- Milligram CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">

    <title>Home</title>

    <style>
        /* Define CSS rules to style links to set initial link color to black and remove underline */
        .black-link {
            color: black;
            text-decoration: none;
        }

        /* Define CSS rules to change link color to blue and add underline on cursor hover */
        .black-link:hover {
            color: blue; /* Change link color to blue on hover */
            text-decoration: underline; /* Add underline on hover */
        }
    </style>
</head>

<body>
    <!-- build layout of website using bootstrap CSS -->
    <div class='container'>
        <br>
        <div class="row">
            <h3>pyRBDomeDB: A pipeline for enhancing RNA-binding protein data</h3>
        </div>
        <div class="row">
            <p>This database compiles results generated by the pyRBDome pipeline to provide improved predictions for protein RNA-binding sites. </p>
            <p> More information about pyRBDome can be found at <a href='about_pyrbdome.php'>About pyRBDome</a></p>
        </div>  
    </div>

    <?php include 'footer_pyrbdome.php'; ?>
    
</body>
</html>