<?php

// This webpage is the home page: contains information about the database as well as brief introduction to the tools and features

session_start(); // Start session management
include 'menu_pyrbdome.php'; // Include menu script to show menu bar
?>

<!-- Specify doctype as HTML and set language to English -->
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Sets character encoding to UTF-8 for proper rendering of text content, and set viewport properties to device width -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Include Bootstrap CSS for pre designed components for responsive websites to enhance website aesthetic -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

    <!-- CSS Reset -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">

    <!-- Milligram CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">

    <title>Home</title>
</head>

<body>
    <!-- Info about webpage -->
    <div class='container'>
        <br>
        <h3>pyRBDomeDB: Enhanced RNA-Binding Protein Data</h3>
        <p>pyRBDomeDB is a curated database compiling enhanced RNA-binding protein data generated by the pyRBDome pipeline. The pipeline utilises an XGBoost model, which combines RNA-binding amino acid prediction results from various individual predictor algorithms including <a href='https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4150784/'>aaRNA</a>, <a href='https://pubmed.ncbi.nlm.nih.gov/35150250/'>PST PRNA</a>, <a href='https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4987955/'>BindUP</a>, <a href='https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2647826/'>FTMap</a>, <a href='https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4028231/'>RNABindRPlus</a>, and <a href='https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4605291/'>DisoRDPbind</a> and <a href='https://pubmed.ncbi.nlm.nih.gov/37421941/'>HydRa</a> to improve protein RNA-binding site predictions.</p>
        <p> More information about pyRBDome and the predictor algorithms used can be found<a href='about_pyrbdome.php'> here.</a></p>
        <div class='row'>
            <!-- Info about website features and tools -->
            <div class='column column-50'>
                <h4>Features:</h4>
                <p><b><a href='filter_pyrbdome.php'>Browse pyRBDome RNA-Binding Prediction Data:</a> </b>Browse and filter pyRBDome RNA-binding site prediction data by several criterion, such as UniProt ID and prediction scores calculated by the XGBoost model or individual prediction algorithms.</p>
                <p><b><a href='sequence_pyrbdome.php'>View RNA-Binding Amino Acid Prediction Plots:</a> </b>Retrieve prediction score plots for a UniProt ID of interest. These plots display the RNA-binding probabilities of each amino acid in the protein sequence determined by the XGBoost model.</p>
                <p><b><a href='jsmol_pyrbdome.php'>Visualise 3D RNA-Binding Protein Prediction Structures:</a> </b>Interactively view the 3D protein structures generated from RNA-binding amino acid prediction results. </p>
                <p><i>Have any comments or feedback about pyRBDomeDB? <a href='feedback_pyrbdome.php'>Fill out our feedback form</a></i></p>
            </div>
            <!-- Image of PDB structure for aesthetics -->
            <div class='column column-50'>
                <img src="Images/A0AV96_biorender.png" alt="A0AV96_biorender" width="90%" height="90%" style="opacity: 0.9;">
                <p style="text-align: center; font-size: 12px; color: #878787;">XGBoost Model RNA-binding Predictions of RNA-binding Protein 47 (A0AV96)</p>
            </div>
        </div>
    </div>

    <?php include 'footer_pyrbdome.php'; ?>
</body>
</html>
